my dog ate my homework
learn-academy-2022-charlie/week-4-assessment-F-Rivers pull request #1
Opened 2022-06-07 17:00 UTC by F-Rivers

# Submitting Week 4 Assessment

### ✅ Completed Files
Mark the following as confirmation that the files in this repository are complete.
- [ x] JavaScript Coding Challenges
- [ x] Ruby Coding Challenges
- [ x] Interview Questions

### 📝 Feedback
If you would like specific feedback on a particular problem please leave details here:

2022-06-08 22:20 UTC, SunkissedQueen requested changes, later dismissed
Frank, I will need you to go through your interview questions and ensure you have placed them in your own words. Since you will be sending changes, I recommend you include a definition, your use of the tool, and something interesting you learn about the tool. Let me know when you have completed this task so I can continue the review.

2022-06-08 22:20 UTC, SunkissedQueen commented on code-challenges.test.js
> +// I got RED
good failure

2022-06-08 22:20 UTC, SunkissedQueen commented on code-challenges.test.js
> +// I got green
green light!!!

2022-06-08 22:20 UTC, SunkissedQueen commented on code-challenges.test.js
> +describe("min_max", () => {
good structure

2022-06-08 22:20 UTC, SunkissedQueen commented on code-challenges.test.js
> +// I got RED
thanks for putting test results

2022-06-08 22:20 UTC, SunkissedQueen commented on code-challenges.test.js
> +// I got green but didn't change anything from when I got red??
That's peculiar

2022-06-08 22:20 UTC, SunkissedQueen commented on code-challenges.test.js
> +// I got green but didn't change anything from when I got red??
strange...everything passes on my side

2022-06-08 22:20 UTC, SunkissedQueen commented on interview-questions.md
> +  Researched answer: Props is a keyword in React, that stands for properties, and is being used for passing data from one component to another. The important part is that the data in props is being p
Your opening looks very similar to  `“Props” is a special keyword in React, which stands for properties and is being used for passing data from one component to another. `

2022-06-08 22:20 UTC, SunkissedQueen commented on ruby-challenges.rb
> +# output --->
appreciate the output

2022-06-08 22:20 UTC, SunkissedQueen commented on ruby-challenges.rb
> +p no_vowels("Frank The Tank")
alright new test variables

2022-06-08 22:20 UTC, SunkissedQueen commented on ruby-challenges.rb
> +def pali_word(word)
nice method

2022-06-10 16:56 UTC, WalkerTexas-coder requested changes
Frank I am putting in a request that you completely rewrite ALL of your answers and use absolutely zero language that comes from articles written by others. Copying and pasting your interview answers is not permitted even if we use proper citation. 

We are not here to test your ability to google but what you can explain in an interview. 

Your assessment will not be accepted until this is complete.

2022-06-10 22:52 UTC, WalkerTexas-coder approved these changes
Alright, Let's go!

2022-06-10 22:52 UTC, WalkerTexas-coder commented on interview-questions.md
> +  Researched answer: A DOM event is used in conjunction with functions that will not run until the DOM event is triggered. The events are written with the syntax of camelCase and written inside of cu
Better! I appreciate it a lot more being in your own words.

2022-06-10 22:52 UTC, WalkerTexas-coder commented on interview-questions.md
> +  Researched answer: Having a OOP style of programming means you're writing code in a manner that is focused on objects, hence the data being stored in objects. All focus points are a sort of bluepri
YES!

2022-06-10 22:52 UTC, WalkerTexas-coder commented on interview-questions.md
> +  Researched answer: Implicit return in Ruby is when the method being returned can run without being called upon by the "return" syntax.
Variable not method but yes!

2022-06-10 22:56 UTC, merged